---
- hosts: all
  become: yes

  pre_tasks:
    - name: "Set env variables"
      lineinfile:
        dest: "/home/vagrant/.bashrc"
        regexp: "^export {{ item.var }}="
        line: "export {{ item.var }}={{ item.value }}"
      with_items:
        - { var: "RACK_ENV", value: "development" }
        - { var: "LC_ALL", value: "en_US.UTF-8" }

    - name: Add autofollow
      lineinfile:
        dest: "/home/vagrant/.bashrc"
        regexp: "^cd /vagrant"
        line: "cd /vagrant"

  roles:
    - role: ntp
    - role: postgresql
    - role: elixir
